const fs = require('fs');
const assert = require('assert');
const runtime = fs.readFileSync('public/post-ad-runtime.js', 'utf8');
const css = fs.readFileSync('public/post-ad-runtime.css', 'utf8');
const update = fs.readFileSync('api-handlers/update-my-ad.js', 'utf8');
const detail = fs.readFileSync('api-handlers/my-ad-detail.js', 'utf8');
const dispatcher = fs.readFileSync('lib/api-dispatcher.js', 'utf8');
const publish = fs.readFileSync('api-handlers/publish-ad.js', 'utf8');
assert(runtime.includes('const MAX_IMAGES = 10'), 'Client max image limit missing');
assert(runtime.includes('name="photos" type="file" multiple'), 'Edit modal multiple file picker missing');
assert(runtime.includes('data-ehm-remove-photo'), 'Edit photo removal action missing');
assert(runtime.includes("fetch(`/api/my-ad-detail?id="), 'Owned ad full-image fetch missing');
assert(runtime.includes('images: editImages'), 'Edit payload does not send full image list');
assert(update.includes('Maximum 10 photos are allowed.'), 'Backend max 10 validation missing');
assert(update.includes('payload.images = images'), 'Backend full image replacement missing');
assert(detail.includes('images: images.slice(0, 10)'), 'Owned detail endpoint does not cap images');
assert(dispatcher.includes("'/api/my-ad-detail'"), 'Owned detail route missing');
assert(publish.includes('body.images.slice(0, 10)'), 'New ad server max 10 enforcement missing');
assert(css.includes('.ehm-edit-gallery'), 'Edit image gallery styling missing');
console.log('User ad image gallery and maximum 10 regression passed.');
